# Generated by Django 3.1 on 2021-05-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='cariation_value',
            new_name='variation_value',
        ),
    ]
